[workspace]
resolver = "3"
members = ["tests", "crates/core", "crates/server", "crates/repositories"]
exclude = []

[profile.release]
opt-level = 3
debug = true
lto = "thin"

[workspace.package]
edition = "2024"
authors = ["V3ktor <v3ktoryt@gmail.com>"]
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"

[workspace.lints.clippy]
all = "warn"
pedantic = "allow"
